name: Deploy to EC2

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Docker login
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login \
            -u "${{ secrets.DOCKER_USERNAME }}" \
            --password-stdin

      - name: Docker Image Pushing
        run: |
          git clone ${{ secrets.CLONE_URL }}
          cd aws-test
          git switch dev
          docker build -t ${{ secrets.DEV_DOCKER_HUB_TAG }} .
          docker push ${{ secrets.DEV_DOCKER_HUB_TAG }}
      - name: Setup SSH
        run: |
          mkdir -p /tmp/sshkey && touch /tmp/sshkey/ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > /tmp/sshkey/ssh
          chmod 600 /tmp/sshkey/ssh

      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeychecking=no -i /tmp/sshkey/ssh ubuntu@${{ secrets.EC2_STAGING_HOST }} << 'EOF'
            set -e

            cd aws-test

            docker compose down

            # docker rmi -f ${{ secrets.DEV_DOCKER_HUB_TAG }}

            docker compose up -d

            # export NVM_DIR="$HOME/.nvm"
            # [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

            # nvm use default

            # cd aws-test

            # git pull origin dev

            # npm install

            # pm2 restart all || pm2 start npm --name "express" -- start

            # pm2 save
          EOF
